language: objective-c
sudo: false
osx_image: xcode8
cache: cocoapods
podfile: CocoaHeadsNL/Podfile
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install --no-rdoc --no-ri cocoapods
  - pod repo update --silent
  - cd CocoaHeadsNL
  - pod install
script:
  - xctool -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
